# Generated by Django 4.1.1 on 2022-09-29 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
