# Generated by Django 4.1.1 on 2022-09-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contactmessage_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
