# Generated by Django 4.1.1 on 2022-09-29 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contactmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ways_to_give', models.CharField(choices=[('Mobile money', 'Mobile money'), ('Bank transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], default='Mobile money', max_length=255)),
                ('amount_to_give', models.CharField(choices=[('$10', '$10'), ('$20', '$20'), ('$50', '$50'), ('$100', '$100'), ('$200', '$200')], default='$200', max_length=255)),
                ('other_amount_to_give', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
