# Generated by Django 4.1.1 on 2022-09-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_donations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
