# Generated by Django 4.1.1 on 2022-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_donations_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_to_give',
            field=models.CharField(choices=[('$10', '$10'), ('$20', '$20'), ('$50', '$50'), ('$100', '$100'), ('$200', '$200'), ('other', 'other')], default='$200', max_length=255),
        ),
    ]
