# Generated by Django 4.1.1 on 2022-09-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_newslettersubscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscriptions',
            new_name='NewsletterSubscription',
        ),
    ]
