# Generated by Django 4.1.1 on 2022-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_newslettersubscriptions_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInvolvedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
