# Generated by Django 4.1.1 on 2022-10-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_getinvolvedlead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summary',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desciprion',
            new_name='details',
        ),
    ]
