# Generated by Django 4.1.1 on 2022-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_donation_ways_to_give'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_to_give',
            field=models.CharField(choices=[('$10', '$10'), ('$20', '$20'), ('$50', '$50'), ('$100', '$100'), ('$200', '$200'), ('Autre', 'Autre')], default='$200', max_length=255),
        ),
    ]
