# Generated by Django 4.1.1 on 2022-10-06 15:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_donation_amount_to_give'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(upload_to='blog/fratured_image')),
                ('content', ckeditor.fields.RichTextField(max_length=5000)),
            ],
        ),
    ]
