# Generated by Django 4.1.1 on 2022-10-06 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autho',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
