# Generated by Django 4.1.1 on 2022-10-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
