# Generated by Django 4.1.1 on 2022-10-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Bonheur Familiale', 'Bonheur Familiale'), ('Vie spirituelle', 'Vie spirituelle'), ('Vie quotidienne', 'Vie quotidienne'), ('Jeunesse', 'Jeunesse')], default='Jeunesse', max_length=255),
        ),
    ]
