# Generated by Django 4.1.1 on 2022-11-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_blog_slug_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Bonheur Familiale', 'Bonheur Familiale'), ('Vie spirituelle', 'Vie spirituelle'), ('Jeunesse', 'Jeunesse'), ('Vie quotidienne', 'Vie quotidienne')], default='Jeunesse', max_length=255),
        ),
    ]
